import pathlib
import json
import instructor
from pydantic import BaseModel, Field
from litellm import acompletion
import cocoindex as coco
from cocoindex.connectors import localfs
from cocoindex.resources.file import FileLike, PatternFilePathMatcher
import os

# Use an instructor client for structured extraction
# Note: You need to set GEMINI_API_KEY or OPENAI_API_KEY in your environment
_instructor_client = instructor.from_litellm(acompletion, mode=instructor.Mode.JSON)

class FileAnalysis(BaseModel):
    file_path: str = Field(..., description="The path of the file.")
    purpose: str = Field(..., description="A brief explanation of what the file does in Vietnamese.")
    key_features: list[str] = Field(..., description="Key features or logic implemented in this file in Vietnamese.")
    data_flow: str = Field(..., description="How data enters and leaves this file in Vietnamese.")

@coco.fn(memo=True)
async def analyze_file(file: FileLike, outdir: pathlib.Path) -> None:
    content = await file.read_text()
    file_path_str = str(file.file_path.path)
    
    # We use a relatively cheap but smart model
    # cocoindex will memoize this, so it only runs once per file change
    result = await _instructor_client.chat.completions.create(
        model="gemini/gemini-1.5-flash", 
        response_model=FileAnalysis,
        messages=[
            {"role": "system", "content": "You are a senior NestJS developer explaining a codebase in Vietnamese. Be concise and professional."},
            {"role": "user", "content": f"Analyze the following TypeScript file located at '{file_path_str}':\n\n```typescript\n{content}\n```"}
        ],
    )
    
    # Write the intermediate JSON result to a temp file in the outdir
    # The filename uses a hash of the path to be unique and stable
    outname = f"{file.file_path.path.stem}_{hash(file_path_str)}.json"
    localfs.declare_file(outdir / outname, result.model_dump_json(indent=2), create_parent_dirs=True)

@coco.fn
async def aggregate_results(outdir: pathlib.Path, module_name: str, target_file: pathlib.Path) -> None:
    # Read all intermediate JSON files generated by analyze_file
    all_json_files = localfs.walk_dir(
        outdir,
        recursive=False,
        path_matcher=PatternFilePathMatcher(included_patterns=["*.json"])
    )
    
    analyses = []
    for _, file_like in all_json_files.items():
        content = await file_like.read_text()
        analyses.append(FileAnalysis.model_validate_json(content))
        
    # Sort for consistent output
    analyses.sort(key=lambda x: x.file_path)
    
    # Generate Markdown content in Vietnamese
    md_content = f"# Giải Thích Chi Tiết - Module {module_name.capitalize()} (`src/{module_name}`)\n\n"
    md_content += f"Module này chịu trách nhiệm quản lý các hoạt động liên quan đến {module_name} trong hệ thống.\n\n"
    
    for analysis in analyses:
        file_name = analysis.file_path.split('/')[-1]
        md_content += f"## `{file_name}`\n"
        md_content += f"**Mục đích:** {analysis.purpose}\n\n"
        md_content += "**Các tính năng chính:**\n"
        for feature in analysis.key_features:
            md_content += f"- {feature}\n"
        md_content += f"\n**Luồng dữ liệu:** {analysis.data_flow}\n\n"
        md_content += "---\n\n"
    
    md_content += f"\n*Tài liệu này được cập nhật tự động bởi CocoIndex Codebase Analyzer.*\n"
        
    # Declare the final target file
    localfs.declare_file(target_file, md_content, create_parent_dirs=True)

@coco.fn
async def app_main(module_name: str) -> None:
    # Resolve paths relative to the script location
    script_dir = pathlib.Path(__file__).parent.absolute()
    project_root = script_dir.parent.parent
    sourcedir = project_root / "src" / module_name
    outdir = script_dir / f".tmp_results_{module_name}"
    target_file = project_root / "docs" / "explanations" / f"{module_name}.md"

    # 1. Scan source files in the module
    files = localfs.walk_dir(
        sourcedir,
        recursive=True,
        path_matcher=PatternFilePathMatcher(included_patterns=["**/*.ts"])
    )
    
    # 2. Mount analysis component for each file (parallel execution)
    await coco.mount_each(analyze_file, files.items(), outdir)
    
    # 3. Aggregate results into the final Markdown file
    await coco.mount(aggregate_results, outdir, module_name, target_file)

# Define the CocoIndex App
# Run with: cocoindex update main.py
app = coco.App(
    coco.AppConfig(name="ModuleAnalyzer"),
    app_main,
    module_name="cart" # You can change this to any module name in src/
)
